package templates

import "text/template"

// RegistryData holds all data needed to render the registry template.
type RegistryData struct {
	RuntimePackage string
	Migrations     []MigrationInfo
}

// MigrationInfo holds data for a single migration in the registry template.
type MigrationInfo struct {
	Name       string // Folder name (e.g., "20260114035749_add_users")
	Alias      string // Import alias (e.g., "m20260114035749")
	ImportPath string // Full import path
}

const registryTemplateContent = `// Code generated by jone. DO NOT EDIT.
package registry

import (
	"{{ .RuntimePackage }}"
{{ range .Migrations }}
	{{ .Alias }} "{{ .ImportPath }}"
{{- end }}
)

var Registrations = []jone.Registration{
{{- range .Migrations }}
	{
		Name: "{{ .Name }}",
		Up:   {{ .Alias }}.Up,
		Down: {{ .Alias }}.Down,
	},
{{- end }}
}
`

// Registry is the parsed template for generating registry.go files.
var Registry = template.Must(template.New("registry").Parse(registryTemplateContent))

// RenderRegistry generates the registry.go content from the given data.
func RenderRegistry(data RegistryData) ([]byte, error) {
	return Render(Registry, data)
}
