package cli

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"github.com/Grandbusta/jone/cmd/jone/templates"
	"github.com/spf13/cobra"
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Initializes a jone project",
	Long:  `Initializes a jone project with the required folder structure and configuration`,
	Run:   initJone,
}

func initJone(cmd *cobra.Command, args []string) {
	cwd, err := os.Getwd()
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to get working directory: %v\n", err)
		os.Exit(1)
	}

	modFilePath := FindOrCreateGoMod(cwd)
	if modFilePath == "" {
		return
	}

	if !JoneDependencyPresent(modFilePath) {
		fmt.Println("jone is not installed in this project.")
		fmt.Printf("To add it, run: go get %s\n", RuntimePackage)
	}

	if err := createJoneFolderAndFiles(cwd); err != nil {
		fmt.Printf("Error creating jone files: %v\n", err)
		return
	}

	fmt.Println("jone init complete.")
}

func createJoneFolderAndFiles(cwd string) error {
	joneFolderPath := filepath.Join(cwd, JoneFolderPath)

	// Create jone folder
	if _, err := os.Stat(joneFolderPath); err != nil {
		if errors.Is(err, os.ErrNotExist) {
			if err := os.Mkdir(joneFolderPath, 0755); err != nil {
				return fmt.Errorf("creating jone folder: %w", err)
			}
		} else {
			return fmt.Errorf("checking jone folder: %w", err)
		}
	}

	// Create jonefile.go
	joneFilePath := filepath.Join(cwd, JoneFilePath)
	if _, err := os.Stat(joneFilePath); err != nil {
		if errors.Is(err, os.ErrNotExist) {
			if err := writeJoneFile(joneFilePath); err != nil {
				return err
			}
		} else {
			return fmt.Errorf("checking jonefile.go: %w", err)
		}
	}

	// Create migrations folder
	migrationsPath := filepath.Join(cwd, MigrationsPath)
	if err := os.MkdirAll(migrationsPath, 0755); err != nil {
		return fmt.Errorf("creating migrations folder: %w", err)
	}

	// Create registry folder with empty registry.go
	registryPath := filepath.Join(migrationsPath, "registry")
	if err := os.MkdirAll(registryPath, 0755); err != nil {
		return fmt.Errorf("creating registry folder: %w", err)
	}

	// Create initial empty registry.go
	registryFile := filepath.Join(registryPath, "registry.go")
	if _, err := os.Stat(registryFile); errors.Is(err, os.ErrNotExist) {
		if err := writeEmptyRegistry(registryFile); err != nil {
			return err
		}
	}

	// Create or update .gitignore at project root
	if err := ensureGitignore(cwd); err != nil {
		return err
	}

	return nil
}

func writeJoneFile(path string) error {
	content, err := templates.RenderJoneFile(templates.JoneFileData{
		RuntimePackage: RuntimePackage,
	})
	if err != nil {
		return fmt.Errorf("rendering jonefile template: %w", err)
	}

	if err := os.WriteFile(path, content, 0o644); err != nil {
		return fmt.Errorf("writing jonefile.go: %w", err)
	}

	return nil
}

func writeEmptyRegistry(path string) error {
	content := fmt.Sprintf(`// Code generated by jone. DO NOT EDIT.
package registry

import %q

var Registrations = []jone.Registration{}
`, RuntimePackage)

	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("writing registry.go: %w", err)
	}

	return nil
}

func ensureGitignore(projectRoot string) error {
	gitignorePath := filepath.Join(projectRoot, ".gitignore")
	runnerEntry := "jone/.runner/"

	// Check if .gitignore exists
	content, err := os.ReadFile(gitignorePath)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			// Create new .gitignore with .runner entry
			return os.WriteFile(gitignorePath, []byte(runnerEntry+"\n"), 0o644)
		}
		return fmt.Errorf("reading .gitignore: %w", err)
	}

	// Check if .runner is already in .gitignore
	lines := string(content)
	if contains(lines, runnerEntry) {
		return nil // Already present
	}

	// Append .runner entry
	newContent := lines
	if len(lines) > 0 && lines[len(lines)-1] != '\n' {
		newContent += "\n"
	}
	newContent += runnerEntry + "\n"

	return os.WriteFile(gitignorePath, []byte(newContent), 0o644)
}

func contains(s, substr string) bool {
	for _, line := range filepath.SplitList(s) {
		if line == substr {
			return true
		}
	}
	// Simple check for substring
	return len(s) >= len(substr) && (s == substr ||
		len(s) > len(substr) && (s[:len(substr)+1] == substr+"\n" ||
			s[len(s)-len(substr)-1:] == "\n"+substr ||
			len(s) > len(substr)+1 && contains(s, "\n"+substr+"\n")))
}
